version: '3.5'

services:

  db:
    image: docker.io/library/postgres:11
    environment:
      - POSTGRES_DB=bmon
      - POSTGRES_USER=bmon
      - POSTGRES_PASSWORD=bmon
    volumes:
      - 'db-data:/var/lib/postgresql/data'

  redis:
    image: docker.io/library/redis

  grafana:
    image: docker.io/grafana/grafana-enterprise
    user: "${UID}"
    volumes:
      - ${ENV_ROOT}/grafana/etc:/etc/grafana
      - ${ENV_ROOT}/grafana/var:/var/lib/grafana
    links:
      - prom
      - alertman
      - loki
    ports:
      - 3000:3000

  loki:
    image: docker.io/grafana/loki
    user: "${UID}"
    volumes:
      - ${ENV_ROOT}/loki:/loki
      - ${ENV_ROOT}/loki/etc:/etc/loki
    links:
      - alertman
    command: -config.file=/etc/loki/local-config.yaml

  prom:
    image: docker.io/prom/prometheus
    user: "${UID}"
    volumes:
      - ${ENV_ROOT}/prom/etc:/etc/prometheus
      - ${ENV_ROOT}/prom/data:/prometheus
    links:
      - alertman
    ports:
      - 9090:9090

  alertman:
    image: docker.io/prom/alertmanager
    user: "${UID}"
    volumes:
      - ${ENV_ROOT}/alertman/config.yml:/etc/alertmanager/config.yml
    command: --config.file=/etc/alertmanager/config.yml

  bitcoind-exporter:
    image: jamesob/bitcoind-prom
    environment:
      - PYTHONUNBUFFERED=1
      - BITCOIN_RPC_HOST
      - BITCOIN_RPC_PORT
      - BITCOIN_RPC_USER
      - BITCOIN_RPC_PASSWORD
    links:
      - bitcoind

  bitcoind:
    image: jamesob/bitcoind:latest
    user: "${UID}"
    volumes:
      - ${ENV_ROOT}/bitcoin/data:/bitcoin/data
    command: bitcoind -datadir=/bitcoin/data -regtest -debug

  promtail:
    image: docker.io/grafana/promtail
    user: "${UID}"
    volumes:
      - ${ENV_ROOT}/promtail:/etc/promtail
      - ${ENV_ROOT}/bitcoin/data/regtest:/bitcoin/data
    command: --config.file=/etc/promtail/config.yml
    links:
      - loki
      - bitcoind

  web:
    image: web
    user: "${UID}"
    build:
      context: .
      dockerfile: ./etc/Dockerfile
    image: bmon-base-image
    environment:
      - BMON_DATABASE_URL=postgres://bmon:bmon@db:5432/bmon
    ports:
      - 8080:8080
    volumes:
      - ./:/src
      - ./etc/docker_entrypoint.sh:/entrypoint.sh
    links:
      - db
    command: bmon-server

  aggregator-celery-worker:
    image: bmon-base-image
    environment:
      - BMON_DATABASE_URL=postgres://bmon:bmon@db:5432/bmon
      - BMON_REDIS_CENTRAL_URL=redis://redis:6379/0
    volumes:
      - ./:/src
      - /home/james/.bitcoind/debug.log:/var/log/bitcoind.log
    links:
      - db
      - redis
    command: celery -A bmon.aggregator_worker.tasks:app worker

  bitcoind-celery-worker:
    image: bmon-base-image
    environment:
      - BMON_DATABASE_URL=postgres://bmon:bmon@db:5432/bmon
      - BMON_REDIS_LOCAL_URL=redis://redis:6379/1
      - BMON_REDIS_CENTRAL_URL=redis://redis:6379/0
    volumes:
      - ./:/src
    links:
      - db
      - redis
      - aggregator-celery-worker
    command: celery -A bmon.bitcoind_worker.tasks:app worker

  bitcoind-watcher:
    image: bmon-base-image
    environment:
      - BMON_DATABASE_URL=postgres://bmon:bmon@db:5432/bmon
      - BMON_REDIS_LOCAL_URL=redis://redis:6379/1
      - BMON_REDIS_CENTRAL_URL=redis://redis:6379/0
      - BMON_BITCOIND_LOG_PATH=/var/log/bitcoind.log
    volumes:
      - ./:/src
      # TODO: this shouldn't be specific to regtest
      - ${ENV_ROOT}/bitcoin/data/regtest/debug.log:/var/log/bitcoind.log
    links:
      - db
      - redis
      - bitcoind-celery-worker
    command: bmon-watch-bitcoind
     
  # receiver:
  #   restart: always
  #   image: bmon/base-image
  #   environment:
  #     - BMON_DATABASE_URL=postgres://bmon:bmon@db:5432/bmon
  #   volumes:
  #     - ./:/src
  #     - ./etc/docker_entrypoint.sh:/entrypoint.sh
  #   depends_on:
  #     - db
  #     - redis
  #     - web
  #   command: bmon-receiver
     
  # generator:
  #   image: bmon/base-image
  #   volumes:
  #     - ./:/src
  #     - ./etc/docker_entrypoint.sh:/entrypoint.sh
  #     - /data/bitcoin:/bitcoin_data:ro
  #     - /home/james/src/bitcoin/src/bitcoin-cli:/bitcoin-cli
  #   # So that we can access bitcoin-rpc ports from the host.
  #   network_mode: host
  #   depends_on:
  #     - web
  #   environment:
  #     - BMON_DATADIR=/bitcoin_data
  #     - BMON_PATH_TO_CLI=/bitcoin-cli
  #     - BMON_SERVER_URL=web:80

volumes:
  db-data:
