# Services that run on the single, centralized bmon server instance.

version: '3.5'

services:

  db:
    image: docker.io/library/postgres:11
    environment:
      - POSTGRES_DB=bmon
      - POSTGRES_USER=bmon
      - POSTGRES_PASSWORD=bmon
    volumes:
      - 'db-data:/var/lib/postgresql/data'

  redis:
    image: docker.io/library/redis
    ports:
      - 6379:6379

  grafana:
    image: docker.io/grafana/grafana-enterprise
    user: "${UID}"
    volumes:
      - ${ENV_ROOT}/grafana/etc:/etc/grafana
      - ${ENV_ROOT}/grafana/var:/var/lib/grafana
    links:
      - prom
      - alertman
      - loki
    ports:
      - 3000:3000

  loki:
    image: docker.io/grafana/loki
    user: "${UID}"
    volumes:
      - ${ENV_ROOT}/loki:/loki
      - ${ENV_ROOT}/loki/etc:/etc/loki
    links:
      - alertman
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100

  prom:
    image: docker.io/prom/prometheus
    user: "${UID}"
    volumes:
      - ${ENV_ROOT}/prom/etc:/etc/prometheus
      - ${ENV_ROOT}/prom/data:/prometheus
    links:
      - alertman
    ports:
      - 9090:9090

  alertman:
    image: docker.io/prom/alertmanager
    user: "${UID}"
    volumes:
      - ${ENV_ROOT}/alertman/config.yml:/etc/alertmanager/config.yml
    command: --config.file=/etc/alertmanager/config.yml
    ports:
      - 9093

  web:
    image: web
    user: "${UID}"
    build:
      context: .
      dockerfile: ./docker/py.Dockerfile
    image: bmon-base-image
    environment:
      - BMON_DATABASE_URL
    ports:
      - 8080:8080
    volumes:
      - ./:/src
    links:
      - db
    command: bmon-server

  aggregator-celery-worker:
    image: bmon-base-image
    environment:
      - BMON_DATABASE_URL
      - BMON_REDIS_CENTRAL_URL=redis://redis:6379/0
    volumes:
      - ./:/src
      - /home/james/.bitcoind/debug.log:/var/log/bitcoind.log
    links:
      - db
      - redis
    command: celery -A bmon.aggregator_worker.tasks:app worker

volumes:
  db-data:
