# Based upon https://grafana.com/docs/grafana-cloud/quickstart/docker-compose-linux/
# and https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html
version: '2'

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    network_mode: "host"
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom:/prometheus
    network_mode: "host"
    ports:
      - 9090:9090
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:2.4.1
    container_name: loki
    network_mode: "host"
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    network_mode: "host"

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    network_mode: "host"

  kib01:
    image: docker.elastic.co/kibana/kibana:7.16.1
    container_name: kib01
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    depends_on:
      - es01
    network_mode: "host"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.2
    container_name: logstash
    restart: unless-stopped
    volumes:
      - ./logstash/logstash.conf:/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    command: "logstash -f /logstash.conf"
    ports:
      - 5044:5044  # for Filebeat
    depends_on:
      - es01
    network_mode: "host"

volumes:
  prom:
  loki-data:
  grafana:
  esdata01:
  esdata02:
