[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "bmon"
description = "A high-level monitoring system for Bitcoin Core"
readme = "README.rst"
requires-python = ">=3.10"
keywords = ["bitcoin"]
license = {text = "MIT License"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    'importlib-metadata; python_version<"3.10"',
    'mitogen @ git+https://git@github.com/jamesob/mitogen.git',
    'fscm @ git+https://git@github.com/jamesob/fscm.git',
    'clii',
    'flask',
    'sqlalchemy',
    'celery[redis]==5.2.7',
]
dynamic = ["version"]

[project.scripts]
bmon-parse = "bmon.logparse:main"
bmon-mon = "bmon.monitor:main"
bmon-server = "bmon.webapp:main"
bmon-migrate = "bmon.db:init_migrate"
bmon-watch-bitcoind = "bmon.bitcoind_worker.watch_logs:main"

[tool.setuptools]
packages = ["bmon"]

[tool.setuptools.dynamic]
version = {attr = "bmon.VERSION"}
