wireguard:

  wg-bmon:
    cidr: 10.33.0.1/22
    port: 51822
    interfaces: [enp2s0, enp3s0]
    pubkey: VyTZTJM5LSOwj7b0cYefPjQp/NWcyZ6euqcWqtk1KDI=
    host: apu2
    # external_peers:
    #   b1.slug: Q3ZHherioK0EY6Rd7O9B1RooHtOJHd6JhsWPTeh/JQ4=, 10.33.0.10

hosts:

  bmon:
    tags: [server]
    ssh_hostname: 10.33.0.2
    check_host_keys: accept
    wireguard:
      wg-bmon: 
        ip: 10.33.0.2
        endpoint: 10.8.1.1
        pubkey: +Bxc6NA3doW9lyKqoVybzsRZ3upH8jQpVA2M5myoUHE=

  bitcoin-01: 
    tags: [bitcoind]
    ssh_hostname: 10.33.0.3
    check_host_keys: accept
    outbound_wireguard: wg-switzerland-01
    wireguard:
      wg-bmon: 
        ip: 10.33.0.3
        a: bitcoin-0.james.bmon.info
        endpoint: 10.8.1.1
        pubkey: /Qzuh/N11tPhzjCmq9+H+OzbeHnDLvniCPgxc+5R8l8=
    bitcoin_docker_tag: jamesob/bitcoind:23.0

  b-01.slug:
    tags: [bitcoind, vagrant]
    ssh_hostname: 10.33.0.20
    username: vagrant
    check_host_keys: accept
    wireguard:
      wg-bmon:
        ip: 10.33.0.20
        endpoint: 10.8.1.1
        a: b-01.slug.james.bmon.info
        pubkey: VzvkMZx+ZpzCmZvgFECohT1pa2QyC40qp7dHFaEzGn8=
    bitcoin_prune: 550 
    bitcoin_dbcache: 1200
    bitcoin_docker_tag: jamesob/bitcoind:22.0

  b-02.slug:
    tags: [bitcoind, vagrant]
    ssh_hostname: 10.33.0.21
    check_host_keys: accept
    username: vagrant
    wireguard:
      wg-bmon:
        ip: 10.33.0.21
        endpoint: 10.8.1.1
        a: b-02.slug.james.bmon.info
        pubkey: t/jLtFWsGaEy/RGp5ehcY7cVIdsKW8d1iJzTTUBmIxU=
    bitcoin_prune: 550 
    bitcoin_dbcache: 1200
    bitcoin_docker_tag: jamesob/bitcoind:0.18.1
        
  b-03.slug:
    tags: [bitcoind, vagrant]
    ssh_hostname: 10.33.0.22
    check_host_keys: accept
    outbound_wireguard: wg-australia-01
    username: vagrant
    wireguard:
      wg-bmon:
        ip: 10.33.0.22
        endpoint: 10.8.1.1
        a: b-03.slug.james.bmon.info
        pubkey: FCuA6MLGa5PuNX95ZKfjo9WodcI2r3u2792wy6gjxSw=
    bitcoin_prune: 550 
    bitcoin_dbcache: 1200
    bitcoin_docker_tag: jamesob/bitcoind:0.19.1

  b-04.slug:
    tags: [bitcoind, vagrant]
    ssh_hostname: 10.33.0.23
    check_host_keys: accept
    outbound_wireguard: wg-japan-01
    username: vagrant
    wireguard:
      wg-bmon:
        ip: 10.33.0.23
        endpoint: 10.8.1.1
        a: b-04.slug.james.bmon.info
        pubkey: L3DN/gKgDT9gF2qrvcybjV09MC9G4zT7u1Lsa34dTR4=
    bitcoin_prune: 550 
    bitcoin_dbcache: 1200
    bitcoin_docker_tag: jamesob/bitcoind:22.0

  ssd-1.ccl:
    tags: [bitcoind]
    ssh_hostname: ssd-1.ccl.bmon.j.co
    check_host_keys: accept
    username: ccl
    wireguard:
      wg-bmon:
        ip: 10.33.0.50
        endpoint: au92.org
        pubkey: 17Zj7t2SD9Yy9BON350GgohO+uJ+84fzO5AtARU+yQE=
    bitcoin_prune: 5000
    bitcoin_dbcache: 3000
    bitcoin_docker_tag: jamesob/bitcoind:master

  ssd-2.ccl:
    tags: [bitcoind]
    ssh_hostname: ssd-2.ccl.bmon.j.co
    check_host_keys: accept
    username: ccl
    wireguard:
      wg-bmon:
        ip: 10.33.0.51
        endpoint: au92.org
        pubkey: 6XVsUu/fhRSqZ5nlysVg+3Sobl/Lx88ej0v02QRhGRY=
    bitcoin_prune: 5000
    bitcoin_dbcache: 3000
    bitcoin_docker_tag: jamesob/bitcoind:bip324-enable
    bitcoin_extra_args: -v2transport=1
