wireguard:

  wg-bmon:
    cidr: 10.33.0.1/22
    port: 51822
    interfaces: [enp2s0, enp3s0]
    pubkey: VyTZTJM5LSOwj7b0cYefPjQp/NWcyZ6euqcWqtk1KDI=
    host: apu2
    # external_peers:
    #   b1.slug: Q3ZHherioK0EY6Rd7O9B1RooHtOJHd6JhsWPTeh/JQ4=, 10.33.0.10

hosts:

  bmon:  # tp-i5-16g-0
    tags: [server]
    wireguard:
      wg-bmon: 
        ip: 10.33.0.2
        endpoint: 10.8.1.1
        pubkey: +Bxc6NA3doW9lyKqoVybzsRZ3upH8jQpVA2M5myoUHE=

  bitcoin-01: 
    tags: [bitcoin]
    check_host_keys: accept
    bitcoin_version: v23.0
    wireguard:
      wg-bmon: 
        ip: 10.33.0.3
        a: bitcoin-0.james.bmon.info
        endpoint: 10.8.1.1
        pubkey: /Qzuh/N11tPhzjCmq9+H+OzbeHnDLvniCPgxc+5R8l8=

  b-01.slug:
    tags: [bitcoin, vagrant]
    ssh_hostname: slug.lan
    ssh_port: 2222
    username: vagrant
    check_host_keys: ignore
    wireguard:
      wg-bmon:
        ip: 10.33.0.20
        endpoint: 10.8.1.1
        a: b-01.slug.james.bmon.info
        pubkey: VzvkMZx+ZpzCmZvgFECohT1pa2QyC40qp7dHFaEzGn8=
    bitcoin_prune: 550 
    bitcoin_dbcache: 1200

  b-02.slug:
    tags: [bitcoin, vagrant]
    ssh_hostname: slug.lan
    ssh_port: 2223
    check_host_keys: ignore
    username: vagrant
    wireguard:
      wg-bmon:
        ip: 10.33.0.21
        endpoint: 10.8.1.1
        a: b-02.slug.james.bmon.info
        pubkey: t/jLtFWsGaEy/RGp5ehcY7cVIdsKW8d1iJzTTUBmIxU=
    bitcoin_prune: 550 
    bitcoin_dbcache: 1200
        
  b-03.slug:
    tags: [bitcoin, vagrant]
    ssh_hostname: slug.lan
    ssh_port: 2224
    check_host_keys: ignore
    username: vagrant
    wireguard:
      wg-bmon:
        ip: 10.33.0.22
        endpoint: 10.8.1.1
        a: b-03.slug.james.bmon.info
        pubkey: FCuA6MLGa5PuNX95ZKfjo9WodcI2r3u2792wy6gjxSw=
    bitcoin_prune: 550 
    bitcoin_dbcache: 1200

  b-04.slug:
    tags: [bitcoin, vagrant]
    ssh_hostname: slug.lan
    ssh_port: 2225
    check_host_keys: ignore
    username: vagrant
    wireguard:
      wg-bmon:
        ip: 10.33.0.23
        endpoint: 10.8.1.1
        a: b-04.slug.james.bmon.info
        pubkey: L3DN/gKgDT9gF2qrvcybjV09MC9G4zT7u1Lsa34dTR4=
    bitcoin_prune: 550 
    bitcoin_dbcache: 1200
