route:
  receiver: pushover
receivers:
  - name: pushover
    pushover_configs:
      - token: ${PUSHOVER_TOKEN}
        user_key: ${PUSHOVER_USER}
        retry: 30m
        message: '{{ .Annotations.summary }}'
        url: "http://alerts.bmon.j.co"
