{
 "title": "Infra",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "5min load average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Mempool sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "bitcoin_mempool_bytes{}", "legendFormat": "{{job}} ({{version}})" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"bitcoin\"}",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}