{
 "title": "Bitcoind",
 "description": "An example bitcoind dashboard.",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Monitored bitcoind hosts",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  name,\n  bitcoin_version AS \"bitcoin version\",\n  bitcoin_gitref as \"git ref\",\n  cpu_info as \"CPU\",\n  memory_bytes / 1024 / 1024 / 1024 as \"memory (GiB)\",\n  bitcoin_gitsha AS \"git commit\"\nFROM bmon_host\nWHERE id in (SELECT distinct on (name) id FROM bmon_host ORDER BY name, id DESC)\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Chain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "UpdateTip occurrence",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(({job=\"bitcoin\"} |~ `UpdateTip:`)[1m])",
     "legendFormat": "{{host}} ({{version}})"
    }
   ]
  },
  {
   "title": "Reorgs (last 30 days)",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  finished_timestamp AS \"time\",\n  format('%s (%s)', bmon_host.name, bmon_host.bitcoin_version),\n  max_height,\n  min_height,\n  old_blockhashes\nFROM bmon_reorgevent INNER JOIN bmon_host ON bmon_reorgevent.host_id = bmon_host.id\nWHERE\n  finished_timestamp >= NOW() - '30 day'::INTERVAL\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DisconnectBlock occurrence",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(({job=\"bitcoin\"} |~ ` Enqueuing BlockDisconnected: `)[1m])",
     "legendFormat": "{{host}} ({{version}})"
    }
   ]
  },
  {
   "title": "Number of chaintips",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_num_chaintips{job=\"bitcoind\"}",
     "legendFormat": "{{hostname}} ({{bitcoin_version}})"
    }
   ]
  },
  { "title": "P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Mean ping time to peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bmon_peerstats.created_at AS \"time\",\n  ping_mean AS metric,\n  format('%s (%s)', bmon_host.name, bmon_host.bitcoin_version) AS legend\nFROM bmon_peerstats JOIN bmon_host ON bmon_peerstats.host_id = bmon_host.id\nWHERE\n  $__timeFilter(bmon_peerstats.created_at)\nGROUP BY\n  bmon_peerstats.created_at,\n  bmon_host.name,\n  bmon_host.bitcoin_version,\n  ping_mean\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bmon_peerstats.created_at AS \"time\",\n  num_peers AS metric,\n  format('%s (%s)', bmon_host.name, bmon_host.bitcoin_version) AS legend\nFROM bmon_peerstats JOIN bmon_host ON bmon_peerstats.host_id = bmon_host.id\nWHERE\n  $__timeFilter(bmon_peerstats.created_at)\nGROUP BY\n  bmon_peerstats.created_at,\n  bmon_host.name,\n  bmon_host.bitcoin_version,\n  num_peers\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mempool size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "bitcoin_mempool_size",
     "legendFormat": "{{hostname}} ({{bitcoin_version}})"
    }
   ]
  },
  {
   "title": "Mempool rejects per day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(timestamp, '1d', 0) as \"time\",\n  count(*) as metric,\n  format('%s (%s)', bmon_host.name, bmon_host.bitcoin_version)\nFROM bmon_mempoolreject JOIN bmon_host on bmon_mempoolreject.host_id = bmon_host.id\nWHERE\n  \"timestamp\" >  now() - interval '30 day'\nGROUP BY \n  $__timeGroup(timestamp, '1d', 0),\n  bmon_host.name,\n  bmon_host.bitcoin_version\nORDER BY 1, bmon_host.bitcoin_version"
    }
   ]
  },
  {
   "title": "Mempool reject frequencies",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(timestamp, '1d', 0) as \"time\",\n  count(*) as metric,\n  format('%s (%s)', bmon_mempoolreject.reason_code, bmon_host.bitcoin_version)\nFROM bmon_mempoolreject JOIN bmon_host on bmon_mempoolreject.host_id = bmon_host.id\nWHERE\n  \"timestamp\" >  now() - interval '30 day'\nGROUP BY \n  $__timeGroup(timestamp, '1d', 0),\n  bmon_mempoolreject.reason_code,\n  bmon_host.bitcoin_version\nORDER BY 1, bmon_host.bitcoin_version"
    }
   ]
  },
  {
   "title": "Mempool reject rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(timestamp, '10m', 0) as \"time\",\n  count(*) as metric,\n  format('%s (%s)', bmon_host.name, bmon_host.bitcoin_version) AS legend\nFROM bmon_mempoolreject JOIN bmon_host ON bmon_mempoolreject.host_id = bmon_host.id\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY \n  $__timeGroup(timestamp, '10m', 0),\n  bmon_host.name,\n  bmon_host.bitcoin_version\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Mempool rejects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(timestamp, '10m', 0) as \"time\",\n  count(*) AS metric,\n  format('%s [%s (%s)]', reason_code, bmon_host.name, bmon_host.bitcoin_version) AS legend\nFROM bmon_mempoolreject JOIN bmon_host ON bmon_mempoolreject.host_id = bmon_host.id\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY $__timeGroup(timestamp, '10m', 0),\n  bmon_host.name,\n  bmon_host.bitcoin_version,\n  reason_code\nORDER BY 1"
    }
   ]
  },
  {
   "title": "infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{hostname}} ({{ mountpoint }})"
    }
   ]
  },
  {
   "title": "Log parse delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - bmon_last_bitcoind_log_seen_at",
     "legendFormat": "{{ hostname }} ({{ bitcoin_version }})"
    }
   ]
  },
  {
   "title": "Mempool activity cache size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "bmon_mempool_activity_cache_size_mibibytes",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Work queue depths",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "targets": [
    { "expr": "bmon_server_event_queue_depth", "legendFormat": "server queue: {{hostname}}" },
    {
     "expr": "bmon_bitcoind_event_queue_depth",
     "legendFormat": "event: {{hostname}}"
    },
    {
     "expr": "bmon_bitcoind_mempool_queue_depth",
     "legendFormat": "mempool: {{hostname}}"
    }
   ]
  },
  {
   "title": "Last block connected at",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - bmon_last_connect_block_at",
     "legendFormat": "{{hostname}} ({{ bitcoin_version }})"
    }
   ]
  }
 ]
}