# Generated by Django 4.1.2 on 2022-10-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('loghash', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='connectblockevent',
            name='version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='connectblockevent',
            name='warning',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
