# Generated by Django 4.1.2 on 2022-10-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0002_logprogress_alter_connectblockevent_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MempoolAccept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('txhash', models.CharField(max_length=80)),
                ('peer_num', models.IntegerField()),
                ('pool_size_txns', models.IntegerField()),
                ('pool_size_kb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessLineError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('listener', models.CharField(max_length=240)),
                ('line', models.CharField(max_length=2048)),
            ],
        ),
    ]
