# Generated by Django 4.1.2 on 2022-10-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0005_blockconnectedevent_blockdisconnectedevent_peer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='bip152_hb_from',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peer',
            name='bip152_hb_to',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peer',
            name='relaytxes',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='peer',
            constraint=models.UniqueConstraint(fields=('host', 'num', 'addr', 'connection_type', 'inbound', 'network', 'services', 'subver', 'version', 'relaytxes', 'bip152_hb_from', 'bip152_hb_to'), name='unique_peer'),
        ),
    ]
