# Generated by Django 4.1.2 on 2022-10-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0006_peer_bip152_hb_from_peer_bip152_hb_to_peer_relaytxes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='bip152_hb_from',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peer',
            name='bip152_hb_to',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
