# Generated by Django 4.1.2 on 2022-10-25 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0009_mempoolreject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mempoolreject',
            name='peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmon.peer'),
        ),
        migrations.AddConstraint(
            model_name='mempoolreject',
            constraint=models.UniqueConstraint(fields=('host', 'timestamp', 'txhash', 'peer_num'), name='unique_reject'),
        ),
    ]
