# Generated by Django 4.1.2 on 2022-10-26 12:34

from django.db import migrations, models
import django.db.models.deletion


def cleanup_rejects(apps, schema_editor):
    MempoolReject = apps.get_model("bmon", "MempoolReject")
    db_alias = schema_editor.connection.alias

    # Remove old pre-taproot junk
    deleted = MempoolReject.objects.using(db_alias).filter(
        models.Q(host__in=['b-02.slug', 'b-03.slug']),
        models.Q(reason__startswith='scriptpubkey') |
        models.Q(reason__startswith="non-mandatory-script-verify-flag")).delete()
    print(f"DELETED {deleted}")


def add_reasoncode(apps, schema_editor):
    MempoolReject = apps.get_model("bmon", "MempoolReject")
    db_alias = schema_editor.connection.alias

    objs = 0

    for rej in MempoolReject.objects.using(db_alias).all():
        rej.reason_code = MempoolReject.get_reason_reject_code(rej.reason)
        rej.save()
        objs += 1

    print(f"Updated {objs} objects")


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0009_mempoolreject'),
    ]

    operations = [
        migrations.RunPython(cleanup_rejects),
        migrations.AddField(
            model_name='mempoolreject',
            name='reason_code',
            field=models.CharField(default='', help_text='A code indicating the rejection reason', max_length=256),
        ),
        migrations.AlterField(
            model_name='mempoolreject',
            name='peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmon.peer'),
        ),
        migrations.AlterField(
            model_name='mempoolreject',
            name='reason',
            field=models.CharField(help_text='The full reason string', max_length=1024),
        ),
        migrations.AlterField(
            model_name='mempoolreject',
            name='reason_data',
            field=models.JSONField(blank=True, default=dict, help_text='Extra data associated with the reason'),
        ),
        migrations.AddConstraint(
            model_name='mempoolreject',
            constraint=models.UniqueConstraint(fields=('host', 'timestamp', 'txhash', 'peer_num'), name='unique_reject'),
        ),
        migrations.RunPython(add_reasoncode),
    ]
