# Generated by Django 4.1.2 on 2022-10-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0011_host_mempoolreject_unique_reject_host_unique_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logprogress',
            old_name='host',
            new_name='hostname',
        ),
    ]
