# Generated by Django 4.1.2 on 2022-10-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0013_remove_peer_unique_peer_blockconnectedevent_hostobj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processlineerror',
            old_name='host',
            new_name='hostname',
        ),
    ]
