# Generated by Django 4.1.2 on 2022-10-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0014_rename_host_processlineerror_hostname'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mempoolreject',
            name='unique_reject',
        ),
        migrations.AddConstraint(
            model_name='mempoolreject',
            constraint=models.UniqueConstraint(fields=('host', 'hostobj', 'timestamp', 'txhash', 'peer_num'), name='unique_reject'),
        ),
    ]
