# Generated by Django 4.1.2 on 2022-10-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0015_remove_mempoolreject_unique_reject_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mempoolreject',
            name='unique_reject',
        ),
        migrations.RemoveConstraint(
            model_name='peer',
            name='unique_peer',
        ),
        migrations.RemoveField(
            model_name='blockconnectedevent',
            name='host',
        ),
        migrations.RemoveField(
            model_name='blockdisconnectedevent',
            name='host',
        ),
        migrations.RemoveField(
            model_name='connectblockdetails',
            name='host',
        ),
        migrations.RemoveField(
            model_name='connectblockevent',
            name='host',
        ),
        migrations.RemoveField(
            model_name='mempoolreject',
            name='host',
        ),
        migrations.RemoveField(
            model_name='peer',
            name='host',
        ),
        migrations.RemoveField(
            model_name='reorgevent',
            name='host',
        ),
        migrations.RemoveField(
            model_name='requestblockevent',
            name='host',
        ),
        migrations.AlterField(
            model_name='blockconnectedevent',
            name='hostobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmon.host'),
        ),
        migrations.AlterField(
            model_name='blockdisconnectedevent',
            name='hostobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmon.host'),
        ),
        migrations.AlterField(
            model_name='connectblockdetails',
            name='hostobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmon.host'),
        ),
        migrations.AlterField(
            model_name='connectblockevent',
            name='hostobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmon.host'),
        ),
        migrations.AlterField(
            model_name='mempoolreject',
            name='hostobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmon.host'),
        ),
        migrations.AlterField(
            model_name='peer',
            name='hostobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmon.host'),
        ),
        migrations.AlterField(
            model_name='reorgevent',
            name='hostobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmon.host'),
        ),
        migrations.AlterField(
            model_name='requestblockevent',
            name='hostobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmon.host'),
        ),
        migrations.AddConstraint(
            model_name='mempoolreject',
            constraint=models.UniqueConstraint(fields=('hostobj', 'timestamp', 'txhash', 'peer_num'), name='unique_reject'),
        ),
        migrations.AddConstraint(
            model_name='peer',
            constraint=models.UniqueConstraint(fields=('hostobj', 'num', 'addr', 'connection_type', 'inbound', 'network', 'services', 'subver', 'version', 'relaytxes', 'bip152_hb_from', 'bip152_hb_to'), name='unique_peer'),
        ),
    ]
