# Generated by Django 4.1.2 on 2022-10-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0017_remove_mempoolreject_unique_reject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
