# Generated by Django 4.1.3 on 2022-11-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0019_peerstats'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='host',
            name='unique_host',
        ),
        migrations.AddField(
            model_name='host',
            name='bitcoin_listen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='host',
            constraint=models.UniqueConstraint(fields=('name', 'cpu_info', 'memory_bytes', 'nproc', 'bitcoin_version', 'bitcoin_gitref', 'bitcoin_gitsha', 'bitcoin_dbcache', 'bitcoin_prune', 'bitcoin_extra', 'bitcoin_listen'), name='unique_host'),
        ),
    ]
