# Generated by Django 4.1.3 on 2022-11-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0020_remove_host_unique_host_host_bitcoin_listen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='bitcoin_listen',
            field=models.BooleanField(default=False),
        ),
    ]
