# Generated by Django 4.1.7 on 2023-04-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0022_host_disabled'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['name'], name='bmon_host_name_88c4dd_idx'),
        ),
        migrations.AddIndex(
            model_name='peerstats',
            index=models.Index(fields=['created_at'], name='bmon_peerst_created_f06d50_idx'),
        ),
    ]
