# Generated by Django 4.1.7 on 2023-04-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0023_host_bmon_host_name_88c4dd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mempoolreject',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
