# Generated by Django 4.2 on 2023-05-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0024_alter_mempoolreject_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDownloadTimeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('blockhash', models.CharField(max_length=80)),
                ('peer_num', models.IntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmon.host')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmon.peer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
