# Generated by Django 4.2 on 2023-05-16 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0025_blockdownloadtimeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderToTipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blockhash', models.CharField(max_length=80)),
                ('height', models.IntegerField()),
                ('saw_header_at', models.DateTimeField(help_text='When we first saw the Saw new header message')),
                ('reconstruct_block_at', models.DateTimeField(help_text='When the (compact)block was reconstructed')),
                ('tip_at', models.DateTimeField(help_text='When the block became tip')),
                ('header_to_tip_secs', models.FloatField(help_text='Time between header seen and new tip appended')),
                ('header_to_block_secs', models.FloatField(help_text='Time between header seen and full block obtained')),
                ('block_to_tip_secs', models.FloatField(help_text='Time between full block obtained and tip updated')),
                ('blocktime_minus_header_secs', models.FloatField(help_text='Difference between blocktime and header seen')),
                ('reconstruction_data', models.JSONField(blank=True, default=dict, help_text='Extra data associated with the block reconstruction')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmon.host')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
