# Generated by Django 4.2 on 2023-10-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmon', '0026_headertotipevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mempoolreject',
            name='wtxid',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
