name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Build containers
      run: docker-compose build test

    - name: create config
      run: |
        pip install .[tests]
        pip install ./infra
        bmon-config

    - name: flake8
      run: |
        docker-compose run --rm -e RUN_DB_MIGRATIONS= test -- bash -c 'flake8 bmon/ && flake8 infra/'

    - name: pytest
      run: |
        bmon-config
        docker-compose run --rm -e RUN_DB_MIGRATIONS= test -- bash -c 'pytest -vv bmon'

    - name: mypy
      run: |
        rm -rf infra/build
        docker-compose run --rm -e RUN_DB_MIGRATIONS= test -- bash -c 'mypy bmon/ && mypy infra/'
