name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Pull test container
      run: docker pull docker.io/jamesob/bmon:test-latest

    - name: create config
      run: |
        pip install .[tests]
        pip install ./infra
        bmon-config

    - name: flake8 + pytest
      run: |
        ./dev test

    - name: mypy
      run: |
        ./dev mypy
